server:
  port: 8080
spring:
    profiles:
       active: dev
    http:
       multipart:
          max-file-size: 500MB
          max-request-size: 500MB
    jackson:
       time-zone: GMT+8
       date-format: yyyy-MM-dd HH:mm:ss